[program:web-fetch]
command=node src/index.js
directory=/root/workspaces/zl/web-fetch
autostart=true
autorestart=true
startretries=3
user=root
environment=NODE_ENV="production",PORT="8080",HTTP_PROXY="http://127.0.0.1:7890",HTTPS_PROXY="http://127.0.0.1:7890"
stdout_logfile=logs/supervisor.log
stderr_logfile=logs/supervisor_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
